// Rally Photo — Lyon Rally Data
RALLIES.push({
  id: "lyon",
  name: "Rally Photo Lyon",
  shortName: "Lyon",
  subtitle: "La capitale des Gaules en photos",
  description: "21 lieux emblematiques du Vieux-Lyon au Parc de la Tete d'Or",
  rulesIntro: "Suivez le parcours du rally a travers",
  rulesHighlight: "21 lieux emblematiques de Lyon",
  mapCenter: [45.757, 4.835],
  mapZoom: 13,
  theme: {
    primary: "#7c2d12",
    primaryLight: "#9a3412",
    accent: "#c2410c",
    accentLight: "#fb923c",
  },
  checkpoints: [
    // --- Vieux-Lyon ---
    {
      id: 1,
      name: "Cathedrale Saint-Jean-Baptiste",
      description: "La primatiale Saint-Jean, chef-d'oeuvre gothique du Vieux-Lyon, avec son horloge astronomique du XIVe siecle.",
      photoHint: "Photographiez la facade depuis la place Saint-Jean.",
      bonusChallenge: "Photo de l'horloge astronomique a l'interieur (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7602,
      lng: 4.8268,
      points: 20,
      info: {
        horaires: "TLJ 8h15-19h45",
        tarifs: "Gratuit",
        duree: "30 min a 1h",
      },
      hints: [
        { text: "Cherchez le plus grand edifice religieux du Vieux-Lyon, au bord de la Saone.", penalty: 5 },
        { text: "Placez-vous sur la grande place pietonne face a l'entree principale de la cathedrale.", penalty: 5 },
        { text: "Reculez jusqu'au centre de la place Saint-Jean pour cadrer toute la facade gothique, rosace incluse.", penalty: 5 },
      ],
    },
    {
      id: 2,
      name: "Traboules du Vieux-Lyon",
      description: "Les celebres passages couverts reliant les rues du Vieux-Lyon, temoins de l'histoire des canuts et marchands de soie.",
      photoHint: "Entrez dans une traboule et photographiez la perspective du passage.",
      bonusChallenge: "Trouvez et photographiez la traboule de la Tour Rose (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7625,
      lng: 4.8275,
      points: 15,
      info: {
        horaires: "Traboules ouvertes env. 7h-19h30",
        notes: "Respecter le silence, ce sont des immeubles habites",
      },
      hints: [
        { text: "Les traboules sont des passages secrets qui traversent les immeubles du Vieux-Lyon.", penalty: 5 },
        { text: "Entrez par une porte cochère rue Saint-Jean ou rue du Boeuf et cherchez un long couloir voute.", penalty: 5 },
        { text: "Une fois dans le passage, cadrez en longueur pour capturer toute la profondeur du couloir jusqu'a la sortie.", penalty: 5 },
      ],
    },
    {
      id: 3,
      name: "Musees Gadagne",
      description: "Dans le plus grand ensemble Renaissance du Vieux-Lyon : musee d'histoire de Lyon et musee des marionnettes du monde.",
      photoHint: "Photographiez la cour interieure Renaissance du batiment.",
      bonusChallenge: "Selfie avec Guignol au musee des marionnettes (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7637,
      lng: 4.8272,
      points: 15,
      info: {
        horaires: "Mercredi-Dimanche 10h30-18h30",
        tarifs: "8\u00A0\u20AC plein tarif, gratuit -18 ans",
      },
      hints: [
        { text: "Cherchez un grand ensemble de batiments Renaissance dans le coeur du Vieux-Lyon.", penalty: 5 },
        { text: "Le musee se trouve rue de Gadagne, juste au nord de la place du Change.", penalty: 5 },
        { text: "Passez le porche d'entree et photographiez la cour interieure avec ses galeries a arcades Renaissance.", penalty: 5 },
      ],
    },
    // --- Fourviere ---
    {
      id: 4,
      name: "Basilique Notre-Dame de Fourviere",
      description: "La basilique emblematique dominant Lyon depuis la colline de Fourviere, un joyau d'architecture du XIXe siecle.",
      photoHint: "Photographiez la basilique depuis l'esplanade avec la vue sur Lyon.",
      bonusChallenge: "Photo panoramique de Lyon depuis l'esplanade (+15 pts bonus)",
      bonusPoints: 15,
      lat: 45.7623,
      lng: 4.8226,
      points: 25,
      info: {
        horaires: "TLJ 7h-19h",
        tarifs: "Gratuit (toits : 8\u00A0\u20AC)",
        duree: "45 min a 1h30",
      },
      hints: [
        { text: "Montez sur la colline qui domine tout Lyon, a l'ouest de la Saone.", penalty: 5 },
        { text: "Prenez le funiculaire depuis le Vieux-Lyon et dirigez-vous vers la grande esplanade devant la basilique.", penalty: 5 },
        { text: "Placez-vous au bord de l'esplanade, dos a la ville, pour cadrer les quatre tours et le fronton de la basilique.", penalty: 5 },
      ],
    },
    {
      id: 5,
      name: "Theatres Romains de Fourviere",
      description: "Le plus ancien theatre romain de France (15 av. J.-C.) et l'Odeon adjacent, au coeur du site antique de Lugdunum.",
      photoHint: "Prenez une photo depuis les gradins avec la scene en contrebas.",
      bonusChallenge: "Posez en orateur romain sur la scene (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7596,
      lng: 4.8198,
      points: 20,
      info: {
        horaires: "TLJ 7h-19h (ete 21h)",
        tarifs: "Gratuit",
        notes: "Festival des Nuits de Fourviere en ete",
      },
      hints: [
        { text: "Le site antique se trouve sur la colline de Fourviere, pas loin de la basilique.", penalty: 5 },
        { text: "Descendez quelques minutes a pied depuis la basilique en direction du sud-ouest pour trouver les ruines romaines.", penalty: 5 },
        { text: "Montez en haut des gradins du grand theatre et cadrez vers le bas pour capturer la scene et l'orchestre en contrebas.", penalty: 5 },
      ],
    },
    // --- Presqu'ile ---
    {
      id: 6,
      name: "Place Bellecour",
      description: "L'une des plus grandes places d'Europe, avec la statue equestre de Louis XIV et la vue sur Fourviere.",
      photoHint: "Photographiez la statue de Louis XIV avec Fourviere en arriere-plan.",
      bonusChallenge: "Trouvez et photographiez la statue du Petit Prince et Saint-Exupery (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7578,
      lng: 4.8320,
      points: 15,
      info: {},
      hints: [
        { text: "Rendez-vous sur la plus grande place de la Presqu'ile, entre le Rhone et la Saone.", penalty: 5 },
        { text: "Cherchez la statue equestre au centre de cette immense place pietonne, face a la colline de Fourviere.", penalty: 5 },
        { text: "Cadrez la statue de Louis XIV en contre-plongee avec la basilique de Fourviere visible a l'arriere-plan, en vous placant cote sud.", penalty: 5 },
      ],
    },
    {
      id: 7,
      name: "Place des Terreaux",
      description: "Place monumentale avec la fontaine Bartholdi (sculpteur de la Statue de la Liberte) et le musee des Beaux-Arts.",
      photoHint: "Capturez la fontaine Bartholdi avec l'Hotel de Ville en arriere-plan.",
      bonusChallenge: "Photo de nuit de la fontaine illuminee OU photo des 69 jets d'eau de Buren (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7676,
      lng: 4.8343,
      points: 15,
      info: {},
      hints: [
        { text: "Direction le nord de la Presqu'ile, vers une grande place avec une fontaine spectaculaire.", penalty: 5 },
        { text: "La fontaine est l'oeuvre de Bartholdi, le sculpteur de la Statue de la Liberte. L'Hotel de Ville est juste a cote.", penalty: 5 },
        { text: "Placez-vous face a la fontaine avec l'Hotel de Ville dans votre dos, puis retournez-vous pour cadrer les deux ensemble.", penalty: 5 },
      ],
    },
    {
      id: 8,
      name: "Opera de Lyon",
      description: "L'Opera de Lyon avec son toit semi-cylindrique spectaculaire signe Jean Nouvel, alliance d'architecture classique et contemporaine.",
      photoHint: "Photographiez le contraste entre la facade classique et le dome moderne.",
      bonusChallenge: "Photo du reflet du batiment dans les vitres du toit (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7676,
      lng: 4.8362,
      points: 15,
      info: {},
      hints: [
        { text: "Juste a cote de la place des Terreaux, cherchez un batiment alliant ancien et ultramoderne.", penalty: 5 },
        { text: "Le toit en demi-cylindre de verre est l'oeuvre de l'architecte Jean Nouvel, pose sur une facade classique du XIXe siecle.", penalty: 5 },
        { text: "Reculez sur la place Louis Pradel pour cadrer le contraste entre les colonnes classiques du rez-de-chaussee et la verriere arrondie au sommet.", penalty: 5 },
      ],
    },
    // --- Croix-Rousse ---
    {
      id: 9,
      name: "Mur des Canuts",
      description: "Le plus grand trompe-l'oeil d'Europe (1200 m\u00B2) rendant hommage aux canuts, les tisserands de soie lyonnais.",
      photoHint: "Photographiez le mur peint en integrant des passants pour jouer sur l'illusion.",
      bonusChallenge: "Recreez la pose d'un personnage peint sur le mur (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7810,
      lng: 4.8318,
      points: 20,
      info: {
        notes: "Boulevard des Canuts, visible 24h/24",
      },
      hints: [
        { text: "Montez dans le quartier de la Croix-Rousse et cherchez une immense fresque murale.", penalty: 5 },
        { text: "Le mur peint se trouve boulevard des Canuts, dans la partie haute du quartier.", penalty: 5 },
        { text: "Placez-vous sur le trottoir d'en face et integrez un passant devant la fresque pour accentuer l'effet trompe-l'oeil.", penalty: 5 },
      ],
    },
    {
      id: 10,
      name: "Traboules de la Croix-Rousse",
      description: "Les traboules du quartier des canuts, plus longues et escarpees que celles du Vieux-Lyon, chargees d'histoire ouvriere.",
      photoHint: "Traversez la traboule de la Cour des Voraces et photographiez l'escalier monumental.",
      bonusChallenge: "Photo de la montee de la Grande Cote depuis le bas (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7720,
      lng: 4.8305,
      points: 15,
      info: {
        notes: "Cour des Voraces : 9 place Colbert / 29 rue Imbert-Colomes",
      },
      hints: [
        { text: "Les traboules de ce quartier sont plus longues et plus pentues que celles du Vieux-Lyon.", penalty: 5 },
        { text: "Trouvez la Cour des Voraces, entree au 9 place Colbert ou au 29 rue Imbert-Colomes.", penalty: 5 },
        { text: "Dans la cour, levez les yeux et cadrez le grand escalier monumental a six etages qui grimpe le long de la facade.", penalty: 5 },
      ],
    },
    // --- Confluence & Sud ---
    {
      id: 11,
      name: "Musee des Confluences",
      description: "Architecture futuriste spectaculaire au confluent du Rhone et de la Saone. Musee de sciences et societes.",
      photoHint: "Photographiez le batiment depuis la pointe de la Confluence pour capturer son architecture unique.",
      bonusChallenge: "Photo du reflet du musee dans l'eau (+15 pts bonus)",
      bonusPoints: 15,
      lat: 45.7326,
      lng: 4.8182,
      points: 25,
      info: {
        horaires: "Mardi-Dimanche 10h30-18h30",
        tarifs: "12\u00A0\u20AC plein tarif, gratuit -18 ans",
        duree: "2h a 3h",
      },
      hints: [
        { text: "Allez tout au sud de Lyon, la ou les deux fleuves se rejoignent.", penalty: 5 },
        { text: "Le musee a une architecture futuriste en forme de nuage metallique, au bout de la pointe de la Confluence.", penalty: 5 },
        { text: "Avancez jusqu'a la pointe sud du quartier Confluence et cadrez le batiment de profil pour capturer sa silhouette deconstructiviste avec l'eau au premier plan.", penalty: 5 },
      ],
    },
    // --- Tete d'Or ---
    {
      id: 12,
      name: "Parc de la Tete d'Or",
      description: "Le plus grand parc urbain de France (117 ha) avec lac, jardin botanique, roseraie et zoo gratuit.",
      photoHint: "Photographiez le lac avec les bateaux ou la grande serre du jardin botanique.",
      bonusChallenge: "Photo devant la roseraie internationale (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7775,
      lng: 4.8560,
      points: 20,
      info: {
        horaires: "TLJ 6h30-22h30 (ete), 6h30-20h30 (hiver)",
        tarifs: "Gratuit",
        duree: "1h a 3h",
      },
      hints: [
        { text: "Dirigez-vous vers le plus grand parc de Lyon, dans le 6e arrondissement.", penalty: 5 },
        { text: "Entrez par la porte principale (porte des Enfants du Rhone) et dirigez-vous vers le lac central ou les serres du jardin botanique.", penalty: 5 },
        { text: "Au bord du lac, cadrez les barques ou pedalos sur l'eau avec la vegetation en arriere-plan, ou photographiez la grande serre du XIXe siecle.", penalty: 5 },
      ],
    },
    // --- Gastronomie ---
    {
      id: 13,
      name: "Les Halles de Lyon Paul Bocuse",
      description: "Le temple de la gastronomie lyonnaise. Fromageries, charcuteries, patisseries et restaurants dans ce marche couvert mythique.",
      photoHint: "Photographiez l'ambiance du marche avec les etals colores.",
      bonusChallenge: "Photo d'une quenelle, d'un saucisson brioche ou d'une tarte aux pralines (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7637,
      lng: 4.8530,
      points: 20,
      info: {
        horaires: "Mardi-Samedi 7h-22h, Dimanche 7h-13h",
        notes: "102 cours Lafayette, 3e arrondissement",
      },
      hints: [
        { text: "Cherchez le grand marche couvert de Lyon, haut lieu de la gastronomie.", penalty: 5 },
        { text: "Les Halles sont au 102 cours Lafayette, dans le 3e arrondissement, pres de la gare de la Part-Dieu.", penalty: 5 },
        { text: "Entrez dans les halles et photographiez les etals les plus colores : fromages, charcuteries ou patisseries, en capturant l'animation du marche.", penalty: 5 },
      ],
    },
    // --- Street art ---
    {
      id: 14,
      name: "Fresque des Lyonnais",
      description: "Immense fresque en trompe-l'oeil de 800 m\u00B2 representant 30 Lyonnais celebres : les freres Lumiere, Saint-Exupery, Paul Bocuse, l'Abbe Pierre...",
      photoHint: "Photographiez la fresque en entier depuis le quai Saint-Vincent.",
      bonusChallenge: "Identifiez et photographiez Paul Bocuse sur la fresque (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7669,
      lng: 4.8258,
      points: 15,
      info: {
        notes: "2 rue de la Martiniere / angle quai Saint-Vincent, 1er arrondissement",
      },
      hints: [
        { text: "Cherchez une grande fresque murale peinte sur un immeuble en bord de Saone, dans le 1er arrondissement.", penalty: 5 },
        { text: "La fresque est a l'angle de la rue de la Martiniere et du quai Saint-Vincent, pres de la passerelle Saint-Vincent.", penalty: 5 },
        { text: "Traversez le quai et placez-vous en face pour cadrer l'ensemble de la fresque de 800 m\u00B2 avec ses 30 personnages celebres.", penalty: 5 },
      ],
    },
    // --- Institut Lumiere ---
    {
      id: 15,
      name: "Institut Lumiere",
      description: "Le berceau du cinema ! La villa des freres Lumiere, ou fut tourne le premier film de l'histoire en 1895.",
      photoHint: "Photographiez la villa Lumiere depuis le jardin.",
      bonusChallenge: "Recreez la scene du premier film \"Sortie de l'usine Lumiere\" devant le hangar (+15 pts bonus)",
      bonusPoints: 15,
      lat: 45.7447,
      lng: 4.8701,
      points: 20,
      info: {
        horaires: "Mardi-Dimanche 10h-18h30",
        tarifs: "9\u00A0\u20AC plein tarif, 7\u00A0\u20AC reduit",
        duree: "1h a 1h30",
        notes: "25 rue du Premier-Film, 8e arrondissement",
      },
      hints: [
        { text: "Rendez-vous dans le 8e arrondissement, la ou le cinema a ete invente.", penalty: 5 },
        { text: "L'Institut Lumiere est au 25 rue du Premier-Film. Cherchez une belle villa bourgeoise avec un jardin.", penalty: 5 },
        { text: "Entrez dans le jardin et reculez pour cadrer la facade Art Nouveau de la villa Lumiere en entier, avec les arbres du parc.", penalty: 5 },
      ],
    },
    // --- Patrimoine & Culture ---
    {
      id: 16,
      name: "Eglise Saint-Nizier",
      description: "Eglise gothique flamboyant au coeur de la Presqu'ile, avec ses deux fleches asymetriques reconnaissables dans le skyline lyonnais.",
      photoHint: "Photographiez la facade gothique depuis la place Saint-Nizier.",
      bonusChallenge: "Photo des fleches de l'eglise au coucher du soleil (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7647,
      lng: 4.8338,
      points: 15,
      info: {
        horaires: "TLJ 8h-19h",
        tarifs: "Gratuit",
      },
      hints: [
        { text: "Cherchez une eglise avec deux fleches de hauteur differente au coeur de la Presqu'ile.", penalty: 5 },
        { text: "L'eglise est situee sur la place Saint-Nizier, entre les rues de Brest et Paul Chenavard.", penalty: 5 },
        { text: "Placez-vous au centre de la place pour cadrer la facade gothique flamboyant avec ses deux fleches asymetriques.", penalty: 5 },
      ],
    },
    {
      id: 17,
      name: "Place des Jacobins",
      description: "Magnifique place ornee d'une fontaine monumentale du XIXe siecle, entouree de facades haussmanniennes classees.",
      photoHint: "Photographiez la fontaine avec les facades haussmanniennes en arriere-plan.",
      bonusChallenge: "Photo du reflet de la fontaine sur le sol mouille apres la pluie ou l'arrosage (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7606,
      lng: 4.8337,
      points: 15,
      info: {
        notes: "Place situee entre Bellecour et Cordeliers, 2e arrondissement",
      },
      hints: [
        { text: "Cherchez une place elegante avec une grande fontaine entre Bellecour et les Cordeliers.", penalty: 5 },
        { text: "La place est au croisement de la rue Edouard-Herriot et de la rue President Carnot.", penalty: 5 },
        { text: "Positionnez-vous face a la fontaine avec les immeubles haussmanniens du XIXe siecle en arriere-plan.", penalty: 5 },
      ],
    },
    {
      id: 18,
      name: "Parc des Hauteurs & Passerelle des Quatre-Vents",
      description: "Sentier panoramique sur la colline de Fourviere reliant la basilique aux theatres romains, avec une passerelle vertigineuse.",
      photoHint: "Photographiez la vue sur Lyon depuis la passerelle ou le chemin panoramique.",
      bonusChallenge: "Photo avec la Tour Incity et la Tour Part-Dieu visibles a l'horizon (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7580,
      lng: 4.8195,
      points: 15,
      info: {
        horaires: "Acces libre TLJ",
        tarifs: "Gratuit",
        notes: "Acces par le cimetiere de Loyasse ou les theatres romains",
      },
      hints: [
        { text: "Montez sur la colline de Fourviere et cherchez un sentier de promenade entre la basilique et les theatres.", penalty: 5 },
        { text: "Le parc longe la crete de la colline. La passerelle metallique enjambe une breche spectaculaire.", penalty: 5 },
        { text: "Depuis la passerelle, cadrez la vue plongeante sur les toits du Vieux-Lyon et les tours de la Part-Dieu a l'horizon.", penalty: 5 },
      ],
    },
    // --- Rive Gauche ---
    {
      id: 19,
      name: "Berges du Rhone",
      description: "Les berges amenagees du Rhone, promenade pietonne et cyclable de 5 km, lieu de vie incontournable des Lyonnais.",
      photoHint: "Photographiez les berges avec les peniches et le quai anime.",
      bonusChallenge: "Selfie sur une peniche-bar ou devant la passerelle du College (+10 pts bonus)",
      bonusPoints: 10,
      lat: 45.7560,
      lng: 4.8405,
      points: 15,
      info: {
        notes: "Promenade de la Guillotiere au parc de la Tete d'Or, acces libre 24h/24",
      },
      hints: [
        { text: "Descendez sur les berges du Rhone, cote est de la Presqu'ile.", penalty: 5 },
        { text: "Les peniches-bars et restaurants sont amarrees entre les ponts de la Guillotiere et Wilson.", penalty: 5 },
        { text: "Placez-vous au bord de l'eau pour cadrer les peniches avec les quais et les facades de la Presqu'ile en arriere-plan.", penalty: 5 },
      ],
    },
    {
      id: 20,
      name: "Halle Tony Garnier",
      description: "Ancienne halle de marche aux bestiaux (1914), chef-d'oeuvre d'architecture industrielle devenue salle de spectacle mythique.",
      photoHint: "Photographiez la facade monumentale de la halle avec ses grands arcs metalliques.",
      bonusChallenge: "Photo des fresques murales de la Cite Tony Garnier a proximite (+15 pts bonus)",
      bonusPoints: 15,
      lat: 45.7327,
      lng: 4.8266,
      points: 20,
      info: {
        notes: "20 place Antonin-Perrin, 7e arrondissement. Visites lors des evenements.",
      },
      hints: [
        { text: "Cherchez un immense batiment industriel du debut du XXe siecle dans le 7e arrondissement.", penalty: 5 },
        { text: "La halle se trouve place Antonin-Perrin, pres du quartier de Gerland. Les fresques murales de la Cite Tony Garnier sont a 5 minutes a pied.", penalty: 5 },
        { text: "Reculez sur la place pour cadrer l'ensemble de la facade avec ses grands arcs en acier et les murs en brique.", penalty: 5 },
      ],
    },
    {
      id: 21,
      name: "Ile Barbe",
      description: "Ile sur la Saone au nord de Lyon, site monastique du Ve siecle, havre de paix verdoyant accessible par une passerelle.",
      photoHint: "Photographiez l'ile depuis les berges ou la passerelle d'acces.",
      bonusChallenge: "Trouvez et photographiez les ruines de l'ancienne abbaye sur l'ile (+15 pts bonus)",
      bonusPoints: 15,
      lat: 45.7938,
      lng: 4.8262,
      points: 20,
      info: {
        horaires: "Acces libre TLJ",
        tarifs: "Gratuit",
        notes: "Accessible par la passerelle depuis le 9e arrondissement ou par bateau-navette",
      },
      hints: [
        { text: "Cherchez une ile boisee sur la Saone, au nord de Lyon, dans le 9e arrondissement.", penalty: 5 },
        { text: "L'ile est accessible par une passerelle pietonne depuis le quai Paul-Sedallian.", penalty: 5 },
        { text: "Depuis la passerelle, cadrez l'ile verdoyante avec la Saone de chaque cote et les vestiges de l'abbaye visibles entre les arbres.", penalty: 5 },
      ],
    },
  ],
});
