// Rally Photo — Normandie Rally Data
RALLIES.push({
  id: "normandie",
  name: "Rally Photo Normandie",
  shortName: "Normandie",
  subtitle: "Une aventure photo a travers la Normandie",
  description: "24 lieux emblematiques de Giverny a la Cote d'Albatre",
  rulesIntro: "Suivez le parcours du rally a travers",
  rulesHighlight: "24 lieux emblematiques de Normandie",
  mapCenter: [48.85, 0.0],
  mapZoom: 8,
  theme: {
    primary: "#1e3a5f",
    primaryLight: "#2c5282",
    accent: "#d97706",
    accentLight: "#fbbf24",
  },
  checkpoints: [
    // --- Giverny area ---
    {
      id: 1,
      name: "Maison & Jardin Claude Monet",
      description: "La maison et les jardins de Claude Monet a Giverny, avec le celebre pont japonais et les nympheas.",
      photoHint: "Photographiez le pont japonais au-dessus du bassin aux nympheas.",
      bonusChallenge: "Photo de groupe devant la maison rose de Monet (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.0757,
      lng: 1.5335,
      points: 25,
      info: {
        horaires: "TLJ 10h-18h",
        tarifs: "13,50\u00A0\u20AC en ligne, gratuit demandeurs d'emploi",
        reouverture: "1er avril",
        duree: "1h30 a 2h",
        notes: "Dessin et peinture INTERDITS",
      },
      hints: [
        { text: "Cherchez un plan d'eau celebre avec des nenuphars", penalty: 5 },
        { text: "Le pont japonais se trouve au fond du jardin d'eau, pres de la sortie", penalty: 5 },
        { text: "Placez-vous sur la rive est du bassin pour cadrer le pont avec les glycines", penalty: 5 },
      ],
    },
    {
      id: 2,
      name: "Jardin & Musee des Impressionnistes",
      description: "Le musee des Impressionnistes a Giverny, dedie au mouvement impressionniste et ses liens avec la region.",
      photoHint: "Prenez une photo a l'entree du musee ou dans le jardin impressionniste.",
      bonusChallenge: "Recreez la pose d'un tableau impressionniste dans le jardin (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.0747,
      lng: 1.5285,
      points: 15,
      info: {
        horaires: "TLJ 10h-18h",
        tarifs: "13\u00A0\u20AC plein tarif, 10\u00A0\u20AC sans emploi",
        reouverture: "27 mars",
        notes: "Exposition \"Avant les Nympheas : Monet Decouvre Giverny\"",
      },
      hints: [
        { text: "Le musee est tout pres de la maison de Monet, dans la meme rue", penalty: 5 },
        { text: "Repérez le jardin paysager a l'entree du musee, ideal pour une photo", penalty: 5 },
        { text: "Placez-vous face a l'entree principale avec les parterres de fleurs au premier plan", penalty: 5 },
      ],
    },
    // --- Vernon ---
    {
      id: 3,
      name: "Vernon \u2014 Vieux Moulin & Collegiale",
      description: "Le pittoresque Vieux Moulin perche sur le pont medieval au-dessus de la Seine, et la Collegiale Notre-Dame.",
      photoHint: "Photographiez l'iconique Vieux Moulin sur le pont medieval.",
      bonusChallenge: "Selfie devant la Collegiale Notre-Dame (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.0929,
      lng: 1.4861,
      points: 15,
      info: {},
      hints: [
        { text: "Le moulin se trouve sur un ancien pont medieval enjambant la Seine", penalty: 5 },
        { text: "Descendez vers les berges de la Seine, cote rive droite, pour apercevoir le moulin", penalty: 5 },
        { text: "Le meilleur point de vue est depuis le Pont Clemenceau, avec le moulin a colombages au centre", penalty: 5 },
      ],
    },
    // --- Les Andelys ---
    {
      id: 4,
      name: "Chateau Gaillard \u2014 Les Andelys",
      description: "La forteresse en ruines construite par Richard Coeur de Lion en 1196, dominant la vallee de la Seine.",
      photoHint: "Photographiez les ruines du chateau avec la boucle de la Seine en contrebas.",
      bonusChallenge: "Posez en chevalier medieval devant les remparts (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.2365,
      lng: 1.4070,
      points: 20,
      info: {
        horaires: "Mercredi-Dimanche 10h-12h30 / 14h-18h",
        tarifs: "3,50\u00A0\u20AC plein tarif, 3\u00A0\u20AC demandeurs d'emploi",
        reouverture: "29 mars",
      },
      hints: [
        { text: "La forteresse domine la vallee de la Seine depuis les hauteurs", penalty: 5 },
        { text: "Montez jusqu'aux ruines par le sentier depuis le Petit-Andely pour voir la boucle de la Seine", penalty: 5 },
        { text: "Placez-vous pres du donjon pour cadrer les remparts avec le meandre de la Seine en contrebas", penalty: 5 },
      ],
    },
    {
      id: 5,
      name: "Eglise Saint-Sauveur \u2014 Les Andelys",
      description: "Belle eglise dans le village du Petit-Andely, au pied du Chateau Gaillard.",
      photoHint: "Prenez une photo de la facade depuis la charmante place du village.",
      bonusChallenge: "Photo avec un detail architectural de l'eglise en gros plan (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.2456,
      lng: 1.4110,
      points: 10,
      info: {},
      hints: [
        { text: "L'eglise se trouve dans le village du Petit-Andely, en contrebas du chateau", penalty: 5 },
        { text: "Cherchez la place centrale du Petit-Andely, l'eglise donne directement dessus", penalty: 5 },
        { text: "Reculez jusqu'au centre de la place pour cadrer toute la facade de l'eglise Saint-Sauveur", penalty: 5 },
      ],
    },
    {
      id: 6,
      name: "Collegiale Notre-Dame \u2014 Les Andelys",
      description: "La grande collegiale du Grand-Andely avec son impressionnante architecture gothique.",
      photoHint: "Capturez la facade complete de la Collegiale depuis la place.",
      bonusChallenge: "Photo des vitraux de l'interieur (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.2478,
      lng: 1.3996,
      points: 10,
      info: {},
      hints: [
        { text: "La collegiale se trouve dans le Grand-Andely, pas le Petit-Andely", penalty: 5 },
        { text: "Cherchez la grande place du Grand-Andely, la collegiale est l'edifice imposant avec ses arcs-boutants", penalty: 5 },
        { text: "Placez-vous au centre de la place face a la facade occidentale pour capturer toute l'architecture gothique", penalty: 5 },
      ],
    },
    // --- Chateau de Gaillon ---
    {
      id: 7,
      name: "Chateau de Gaillon",
      description: "Un des premiers chateaux Renaissance de France, a l'architecture remarquable.",
      photoHint: "Photographiez le portail Renaissance du chateau.",
      bonusChallenge: "Photo panoramique de la cour interieure (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.2277,
      lng: 1.3374,
      points: 15,
      info: {
        reouverture: "1er avril",
      },
      hints: [
        { text: "Le chateau est perche sur les hauteurs du village de Gaillon", penalty: 5 },
        { text: "Repérez l'entree principale avec son portail Renaissance richement decore", penalty: 5 },
        { text: "Placez-vous face au portail d'entree pour capturer les details sculptes de style Renaissance italienne", penalty: 5 },
      ],
    },
    // --- Rouen ---
    {
      id: 8,
      name: "Cathedrale & Gros-Horloge \u2014 Rouen",
      description: "La Cathedrale gothique peinte par Monet, la Rue Saint-Romain, le celebre Gros-Horloge, la Rue du Gros et la Rue des Chanoines (une des rues les plus petites de Rouen).",
      photoHint: "Recreez la vue de Monet : photographiez la facade de la Cathedrale, puis le Gros-Horloge dans sa rue pietonne.",
      bonusChallenge: "Prenez la meme photo de la Cathedrale a deux moments differents de la journee, comme Monet (+15 pts bonus)",
      bonusPoints: 15,
      lat: 49.4401,
      lng: 1.0941,
      points: 20,
      info: {},
      hints: [
        { text: "Monet a peint cette cathedrale plus de 30 fois depuis le meme endroit", penalty: 5 },
        { text: "Cherchez la Rue du Gros-Horloge, face a la cathedrale, pour retrouver l'angle de Monet", penalty: 5 },
        { text: "Placez-vous dans la rue pietonne en face de la facade ouest, a environ 50 metres, pour cadrer les deux tours", penalty: 5 },
      ],
    },
    {
      id: 9,
      name: "Quartier Saint-Maclou \u2014 Rouen",
      description: "L'Eglise Saint-Maclou (chef-d'oeuvre du gothique flamboyant), l'Aitre Saint-Maclou (ancien cimetiere a colombages), les rues Martainville, Damiette et Eau-de-Robec.",
      photoHint: "Photographiez la facade flamboyante de l'Eglise Saint-Maclou ou la cour de l'Aitre.",
      bonusChallenge: "Trouvez et photographiez les sculptures macabres de l'Aitre Saint-Maclou (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.4393,
      lng: 1.0990,
      points: 15,
      info: {
        notes: "Rues pittoresques a ne pas manquer : rue Martainville, rue Damiette, rue Eau-de-Robec",
      },
      hints: [
        { text: "Le quartier se trouve a l'est de la cathedrale, autour de l'eglise Saint-Maclou", penalty: 5 },
        { text: "L'Aitre Saint-Maclou est un ancien cimetiere medieval entoure de galeries a colombages, cherchez l'entree dans la rue Martainville", penalty: 5 },
        { text: "Placez-vous face au porche de l'eglise Saint-Maclou pour capturer les cinq arches flamboyantes de la facade", penalty: 5 },
      ],
    },
    {
      id: 10,
      name: "Vieux-Marche, Saint-Ouen & Musees \u2014 Rouen",
      description: "La Place du Vieux-Marche et l'Eglise Jeanne d'Arc, l'Abbatiale Saint-Ouen, le Musee des Beaux-Arts (gratuit), le Palais de Justice et l'Hotel de Bourgtheroulde.",
      photoHint: "Photographiez l'Eglise Jeanne d'Arc sur la Place du Vieux-Marche ou la facade de l'Abbatiale Saint-Ouen.",
      bonusChallenge: "Selfie devant le Palais de Justice ou l'Hotel de Bourgtheroulde (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.4433,
      lng: 1.0880,
      points: 15,
      info: {
        tarifs: "Musee des Beaux-Arts : gratuit",
      },
      hints: [
        { text: "La Place du Vieux-Marche est l'endroit ou Jeanne d'Arc a ete brulee en 1431", penalty: 5 },
        { text: "L'eglise moderne Sainte-Jeanne-d'Arc se trouve sur la place, avec ses vitraux du XVIe siecle", penalty: 5 },
        { text: "Depuis le centre de la Place du Vieux-Marche, cadrez l'eglise avec la croix commemorative de Jeanne d'Arc au premier plan", penalty: 5 },
      ],
    },
    // --- Foret de Lyons ---
    {
      id: 11,
      name: "Foret de Lyons-la-Foret",
      description: "L'une des plus belles hetraies de France. Le charmant village de Lyons-la-Foret avec ses maisons a colombages.",
      photoHint: "Prenez une photo sous les grands hetres ou sur la place du village.",
      bonusChallenge: "Photo d'un arbre remarquable de la foret (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.3989,
      lng: 1.4726,
      points: 15,
      info: {},
      hints: [
        { text: "Le village est au coeur d'une des plus belles hetraies de France", penalty: 5 },
        { text: "La place centrale du village est entouree de maisons a colombages et de halles anciennes", penalty: 5 },
        { text: "Placez-vous sous les halles du marche pour photographier la place avec les facades a colombages", penalty: 5 },
      ],
    },
    // --- Chateau de Vascoeuil ---
    {
      id: 12,
      name: "Chateau de Vascoeuil",
      description: "Un charmant chateau transforme en centre d'art, entoure d'un jardin de sculptures en pleine campagne normande.",
      photoHint: "Photographiez une sculpture avec le chateau en arriere-plan.",
      bonusChallenge: "Imitez la pose d'une des sculptures du jardin (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.4296,
      lng: 1.3820,
      points: 15,
      info: {},
      hints: [
        { text: "Le chateau est entoure d'un parc de sculptures en pleine campagne", penalty: 5 },
        { text: "Promenez-vous dans le jardin et cherchez une sculpture avec le chateau visible derriere", penalty: 5 },
        { text: "Positionnez-vous dans l'allee principale du jardin pour cadrer une sculpture au premier plan et la tour du chateau en arriere-plan", penalty: 5 },
      ],
    },
    // --- Abbaye de Jumieges ---
    {
      id: 13,
      name: "Abbaye de Jumieges",
      description: "Les ruines majestueuses de l'une des plus anciennes et belles abbayes de France, le long de la Seine.",
      photoHint: "Capturez les hautes ruines jumelles de la nef \u2014 la plus belle ruine de France !",
      bonusChallenge: "Photo a travers une arche avec le ciel visible (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.4314,
      lng: 0.8182,
      points: 20,
      info: {
        horaires: "TLJ 9h30-13h / 14h30-17h30",
        tarifs: "7,50\u00A0\u20AC plein tarif, gratuit demandeurs d'emploi",
        notes: "Belles promenades dans le parc paysager",
      },
      hints: [
        { text: "Les ruines de l'abbaye sont considerees comme les plus belles de France", penalty: 5 },
        { text: "Cherchez les deux hautes tours jumelles de la nef, encore debout apres des siecles", penalty: 5 },
        { text: "Placez-vous dans l'allee centrale de la nef pour cadrer les deux tours jumelles se decoupant contre le ciel", penalty: 5 },
      ],
    },
    // --- Saint-Wandrille ---
    {
      id: 14,
      name: "Abbaye Saint-Wandrille",
      description: "Abbaye benedictine vivante fondee en 649, toujours habitee par une trentaine de moines. Ruines de l'ancienne abbatiale et eglise actuelle.",
      photoHint: "Photographiez le cloitre ou la grande entree de l'abbaye.",
      bonusChallenge: "Ramenez une photo d'un produit des moines (biere, cire) (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.5288,
      lng: 0.7646,
      points: 15,
      info: {
        horaires: "TLJ 5h15-13h / 14h-21h15, visite guidee 15h30",
        tarifs: "Gratuit sauf visite guidee 5\u00A0\u20AC",
        notes: "Encore une trentaine de moines. Site des ruines de l'ancienne abbatiale et eglise actuelle",
      },
      hints: [
        { text: "Cette abbaye benedictine est toujours habitee par des moines", penalty: 5 },
        { text: "Le cloitre medieval est le joyau de l'abbaye, cherchez-le apres l'entree principale", penalty: 5 },
        { text: "Photographiez depuis l'allee d'entree pour cadrer le porche monumental avec les batiments conventuels", penalty: 5 },
      ],
    },
    // --- Chateau du Champ de Bataille ---
    {
      id: 15,
      name: "Chateau du Champ de Bataille",
      description: "Splendide chateau du XVIIe siecle avec des jardins a la francaise spectaculaires.",
      photoHint: "Prenez une photo panoramique des grands jardins depuis la terrasse.",
      bonusChallenge: "Photo avec une perspective parfaite dans l'axe des jardins (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.1613,
      lng: 0.8354,
      points: 20,
      info: {
        horaires: "Jardins Mercredi-Dimanche 10h-17h30",
        tarifs: "15\u00A0\u20AC plein tarif, 13\u00A0\u20AC demandeurs d'emploi",
        reouverture: "4 avril",
        duree: "1h30 a 3h",
      },
      hints: [
        { text: "Le chateau possede des jardins a la francaise spectaculaires", penalty: 5 },
        { text: "Montez sur la terrasse du chateau pour avoir une vue plongeante sur les jardins", penalty: 5 },
        { text: "Depuis la terrasse centrale, cadrez l'axe principal des jardins avec les parterres symetriques en perspective", penalty: 5 },
      ],
    },
    // --- Le Bec-Hellouin ---
    {
      id: 16,
      name: "Le Bec-Hellouin",
      description: "Adorable village classe \"Plus Beaux Villages de France\". Maisons a colombages et Abbaye Notre-Dame du Bec.",
      photoHint: "Photographiez les maisons a colombages ou l'entree de l'abbaye.",
      bonusChallenge: "Trouvez et photographiez la plus belle maison a colombages du village (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.2316,
      lng: 0.7215,
      points: 15,
      info: {
        horaires: "Abbaye : visite libre parc et eglise abbatiale TLJ 8h-21h",
        notes: "\"Plus Beaux Villages de France\"",
      },
      hints: [
        { text: "Ce village est classe parmi les Plus Beaux Villages de France", penalty: 5 },
        { text: "Flânez dans la rue principale bordee de maisons a colombages fleuries", penalty: 5 },
        { text: "Les plus belles maisons a colombages se trouvent dans la rue principale menant a l'abbaye, photographiez-les avec les fleurs aux fenetres", penalty: 5 },
      ],
    },
    // --- Bernay ---
    {
      id: 17,
      name: "Bernay",
      description: "Charmante ville avec colombages, l'Eglise Abbatiale et l'Eglise Sainte-Croix.",
      photoHint: "Capturez la plus belle rue a colombages ou la facade de l'Eglise Abbatiale.",
      bonusChallenge: "Photo d'un detail de colombage en gros plan (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.0895,
      lng: 0.5980,
      points: 10,
      info: {},
      hints: [
        { text: "Bernay est une ville aux nombreuses rues a colombages", penalty: 5 },
        { text: "L'Eglise Abbatiale se trouve dans le centre historique, cherchez les rues pietonnes", penalty: 5 },
        { text: "Depuis la Rue Thiers, cadrez la facade romane de l'Eglise Abbatiale avec les maisons a colombages de chaque cote", penalty: 5 },
      ],
    },
    // --- Vieux-Port ---
    {
      id: 18,
      name: "Vieux-Port",
      description: "Adorable village. Route des Chaumieres avec ses toits de chaume. Sentier de randonnee (30 min) jusqu'a la Chapelle Saint-Thomas.",
      photoHint: "Parcourez la Route des Chaumieres et photographiez les chaumieres au toit de chaume.",
      bonusChallenge: "Randonnez jusqu'a la Chapelle Saint-Thomas et prenez une photo (+15 pts bonus)",
      bonusPoints: 15,
      lat: 49.4156,
      lng: 0.5025,
      points: 15,
      info: {
        duree: "Rando 30 min jusqu'a la Chapelle Saint-Thomas",
      },
      hints: [
        { text: "Cherchez la Route des Chaumieres, une petite route bordee de maisons au toit de chaume", penalty: 5 },
        { text: "Les plus belles chaumieres se trouvent le long de la route principale traversant le village", penalty: 5 },
        { text: "Arretez-vous devant les chaumieres aux toits de chaume les mieux conservees et cadrez-les avec la vegetation normande", penalty: 5 },
      ],
    },
    // --- Marais-Vernier ---
    {
      id: 19,
      name: "Le Marais-Vernier",
      description: "Les plus belles fermes de Normandie avec leurs toits de chaume. Magnifique a velo (itineraire La Seine a Velo).",
      photoHint: "Photographiez les fermes aux toits de chaume \u2014 les plus belles de Normandie !",
      bonusChallenge: "Photo a velo sur l'itineraire La Seine a Velo (+15 pts bonus)",
      bonusPoints: 15,
      lat: 49.4003,
      lng: 0.4469,
      points: 20,
      info: {
        notes: "A velo c'est top ! Itineraire La Seine a Velo. Chambres d'hotes : \"Les Cigognes\", \"La Route des Chaumieres\"",
      },
      hints: [
        { text: "Le Marais-Vernier abrite les plus belles fermes au toit de chaume de Normandie", penalty: 5 },
        { text: "Parcourez les petites routes de campagne autour du marais pour trouver les fermes traditionnelles", penalty: 5 },
        { text: "Les fermes les plus photogeniques se trouvent le long des routes bordant le marais, cadrez les toits de chaume avec les pommiers normands", penalty: 5 },
      ],
    },
    // --- Honfleur ---
    {
      id: 20,
      name: "Honfleur",
      description: "Petit port normand pittoresque. Eglise Saint-Leonard, Jardin du Tripot, Greniers a Sel, le Vieux Bassin, la Lieutenance, l'Eglise Sainte-Catherine.",
      photoHint: "Photographiez les facades colorees du Vieux Bassin avec la tour de la Lieutenance.",
      bonusChallenge: "Photo de l'interieur de l'Eglise Sainte-Catherine (toute en bois !) (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.4185,
      lng: 0.2331,
      points: 20,
      info: {},
      hints: [
        { text: "Le Vieux Bassin est le coeur historique de Honfleur, borde de facades colorees", penalty: 5 },
        { text: "Cherchez la tour de la Lieutenance a l'entree du Vieux Bassin, cote quai", penalty: 5 },
        { text: "Placez-vous sur le quai Sainte-Catherine, face au Vieux Bassin, pour cadrer les facades colorees avec la Lieutenance sur la droite", penalty: 5 },
      ],
    },
    // --- Cote d'Albatre ---
    {
      id: 21,
      name: "Falaises d'Etretat",
      description: "Falaise d'Aval et sa Porte, l'Aiguille, la Manneporte (acces en 25 min depuis le Perrey), le Trou a l'Homme, la Falaise d'Amont (courage pour la montee !) et l'Aiguille de Belval.",
      photoHint: "Capturez l'Aiguille et la Porte d'Aval \u2014 meilleure vue depuis le haut de la Falaise d'Amont !",
      bonusChallenge: "Prenez la pose mysterieuse d'Arsene Lupin devant l'Aiguille (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.7071,
      lng: 0.2049,
      points: 20,
      info: {
        notes: "L'Aiguille creuse \u2014 Maurice Leblanc (Arsene Lupin). La Manneporte : arche imposante, acces 25 min depuis le Perrey",
      },
      hints: [
        { text: "Les falaises de craie blanche sont visibles depuis la plage d'Etretat", penalty: 5 },
        { text: "Prenez le sentier du GR21 vers la falaise d'Aval pour voir l'Aiguille et l'arche", penalty: 5 },
        { text: "Depuis le haut de la falaise d'Amont (cote chapelle), cadrez l'Aiguille et la Porte d'Aval ensemble pour la photo iconique", penalty: 5 },
      ],
    },
    {
      id: 22,
      name: "Village d'Etretat",
      description: "Les Jardins d'Etretat, les vieilles halles, le vieux marche, l'eglise Notre-Dame et le Clos Lupin (maison de Maurice Leblanc, createur d'Arsene Lupin).",
      photoHint: "Photographiez les Jardins d'Etretat avec vue sur les falaises, ou le Clos Lupin.",
      bonusChallenge: "Photo devant le Clos Lupin, maison d'Arsene Lupin (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.7065,
      lng: 0.2070,
      points: 15,
      info: {
        horaires: "Jardins d'Etretat : TLJ 10h-17h30",
        tarifs: "Jardins : 12,90\u00A0\u20AC plein tarif",
        duree: "Temps sur place minimum 1h",
      },
      hints: [
        { text: "Les Jardins d'Etretat sont perches sur la falaise, avec une vue spectaculaire", penalty: 5 },
        { text: "Le Clos Lupin se trouve dans le centre du village, c'est la maison-musee de Maurice Leblanc", penalty: 5 },
        { text: "Depuis les Jardins d'Etretat, cadrez les sculptures vegetales avec les falaises en arriere-plan", penalty: 5 },
      ],
    },
    // --- Fecamp ---
    {
      id: 23,
      name: "Fecamp",
      description: "L'Abbatiale de la Sainte-Trinite, le Palais de la Benedictine (visite, degustation, musee et cave) et le panorama depuis le Cap Fagnet, point de vue le plus eleve de la Cote d'Albatre.",
      photoHint: "Photographiez le panorama depuis le Cap Fagnet ou la facade du Palais de la Benedictine.",
      bonusChallenge: "Photo du panorama complet depuis le Cap Fagnet (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.7579,
      lng: 0.3725,
      points: 20,
      info: {
        tarifs: "Palais de la Benedictine : 25\u00A0\u20AC (visite, degustation, musee, cave)",
        notes: "Cap Fagnet : parking ou montee par le sentier des matelots. Point de vue le plus eleve de la Cote d'Albatre",
      },
      hints: [
        { text: "Fecamp est un port de la Cote d'Albatre, domine par le Cap Fagnet", penalty: 5 },
        { text: "Le Palais de la Benedictine est un batiment remarquable dans le centre-ville, impossible a rater", penalty: 5 },
        { text: "Montez au Cap Fagnet par le sentier des matelots pour le panorama le plus eleve de toute la Cote d'Albatre", penalty: 5 },
      ],
    },
    // --- Saint-Valery-en-Caux ---
    {
      id: 24,
      name: "Saint-Valery-en-Caux",
      description: "La Maison Henry IV, la Rue des Penitents, la Falaise d'Aval (acces depuis le quai d'Aval). Balade de 2 km a l'entree de la ruelle qui longe la Maison Henry IV.",
      photoHint: "Photographiez la Maison Henry IV ou la Falaise d'Aval depuis le quai.",
      bonusChallenge: "Faites la balade de 2 km et photographiez la vue sur les falaises (+10 pts bonus)",
      bonusPoints: 10,
      lat: 49.8710,
      lng: 0.7105,
      points: 15,
      info: {
        duree: "Balade 2 km depuis la ruelle longeant la Maison Henry IV",
        notes: "Falaise d'Aval : acces depuis le quai d'Aval",
      },
      hints: [
        { text: "Saint-Valery-en-Caux est une petite station balneaire de la Cote d'Albatre", penalty: 5 },
        { text: "La Maison Henry IV est un batiment historique a colombages pres du port", penalty: 5 },
        { text: "Depuis le quai d'Aval, photographiez la Falaise d'Aval avec le port au premier plan", penalty: 5 },
      ],
    },
  ],
});
